### ISSUE TITLE
Duplicate record Worldwound Incursion

### ISSUE THREAD

**Issue by Auspician** [shadowchemosh/HL-Pack-GM#4]
When loading the Basic Pack and the GM Mythic Pack there is a duplicate record issue. Here is the exact text of the error:

File: COM_BasicPack_AP073 - The Worldwound Incursion.user (line 72) - Thing - Duplicate record encountered ('pAP73Wards')
File: COM_GMMythicPack_AP073 - The Worldwound Incursion.user (line 4) - Thing - Duplicate record encountered ('pAP73BrkLg')

**Comment by Auspician** [comment]
This seems to be fixed when you don't have the Basic Pack installed as well (which is pointless as it is already included in the others packs, but that information is not immediately accessible through Hero Lab so it still is likely worth fixing). Low priority.

**Comment by shadowchemosh** [comment]
So this goes back to a "load" issue with the installer not the files themselves.  Both the GM/Mythic Pack can play perfectly fine together on the same computer.  This is proven by the very fact that the Basic Pack is inside the GM Pack so that sort of proves they can play together.  The issue is in the installer and on some computers it requires multiple installs to get all the files moved over correctly.  I am going to assume you deleted the Basic Pack and then reinstalled the GM Pack again to get it work.  There for installing the GM Pack multiple times.

Colen at LW has asked that anyone with these 'Duplicate' install issues please email LW support so they can work with you in debugging the issue. support@wolflair.com
